default: &default
 adapter: postgresql
 encoding: unicode
 pool: 5
 timeout: 5000

development:
 <<: *default
 database: dev_survey

test:
 <<: *default
 database: test_survey

production:
  <<: *default
  database: eval-me_production
  username: eval-me
  password: <%= ENV['MYAPP_DATABASE_PASSWORD'] %>
