# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ceb0c0b3d61e681420cfcf0df6110f29499b043509a474be73dbdfb0d3433837af5ee5c3e5491bff0afbaa2cac806ea2bf2a956a8da5b4f3bcb3a80bff594f92

test:
  secret_key_base: 27a2391e2594256a865ef079374f9ce5e5e3e9c71faa52566b4e18735e0b467d6f62f105a741c50b602e7805b7cb459cddd10b6820ac83b579c4851618cedfe6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
